--- 
services:

  genesis:
    image: mysten/sui-tools:mainnet-v1.55.0-arm64
    container_name: genesis
    volumes:
      - ./genesis.yaml:/root/genesis.yaml:ro
      - genesis_config:/root/.sui/sui_config
      - ./genesis/entrypoint.sh:/root/entrypoint.sh:rox
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=trace
      - EPOCH=${EPOCH:-600000} # default epoch duration is 10 minutes
    entrypoint: ["/root/entrypoint.sh"]
  
  prometheus:
    image: prom/prometheus:v3.5.0
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:12.1.1
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3000:3000"

  node-exporter:
    image: prom/node-exporter:v1.9.1
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"

  stress:
    image: stress:testing
    depends_on:
      fullnode:
        condition: service_started
    environment:
      - RUST_BACKTRACE=1
      - STARTUP_DELAY_SECONDS=5
      - STRESS_STAGGERED_START_MAX_MULTIPLIER=0
      - FULLNODE_RPC_ADDRESS=fullnode:9000
      - PRIMARY_GAS_OWNER=0xca97774fbdbf7539aa14cfad491a227661284e3a3d0b97e6365438745beca509
      - GENESIS_BLOB_PATH=/opt/sui/config/genesis.blob
      - KEYSTORE_PATH=/root/sui.keystore
      - STRESS_TARGET_QPS=100
      - STRESS_SHARED_COUNTER=50
      - STRESS_TRANSFER_OBJECT=50
      - STRESS_DELEGATION=0
      - SUI_PROTOCOL_CONFIG_CHAIN_OVERRIDE=${SUI_PROTOCOL_CONFIG_CHAIN_OVERRIDE}
      - BATCH_PAYMENT=1
      - BATCH_PAYMENT_SIZE=15
      - STRESS_ADVERSARIAL=0
    volumes:
      - genesis_config:/opt/sui/config:ro
      - ./stress/sui.keystore:/root/sui.keystore:ro

  fullnode:
    image: mysten/sui-node:mainnet-v1.55.0-arm64
    depends_on:
      genesis:
        condition: service_completed_successfully
    container_name: fullnode
    ports:
      - "9000:9000"
    volumes:
      - ./fullnode/fullnode.yaml:/root/fullnode.yaml:ro
      - fullnode_db:/root/.sui/sui_config
      - genesis_config:/opt/sui/config:ro
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=off
    command: ["sui-node", "--config-path", /root/fullnode.yaml]
  
  validator0:
    image: mysten/sui-node:mainnet-v1.55.0-arm64
    depends_on:
      genesis:
        condition: service_completed_successfully
    container_name: validator0
    ports:
      - "9184:9184"
    entrypoint: ["/root/entrypoint.sh"]
    volumes:
      - ./validator/entrypoint.sh:/root/entrypoint.sh:rox
      - validator0_db:/root/.sui/sui_config
      - genesis_config:/opt/sui/config:rw
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=off
      - NAME=validator0
      - RPC_PORT=9184
    command: ["sui-node", "--config-path", /opt/sui/config/validator0-8080.yaml]

  validator1:
    image: mysten/sui-node:mainnet-v1.55.0-arm64
    depends_on:
      genesis:
        condition: service_completed_successfully
    container_name: validator1
    ports:
      - "9185:9185"
    entrypoint: ["/root/entrypoint.sh"]
    volumes:
      - ./validator/entrypoint.sh:/root/entrypoint.sh:rox
      - validator1_db:/root/.sui/sui_config
      - genesis_config:/opt/sui/config:rw
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=off
      - NAME=validator1
      - RPC_PORT=9185
    command: ["sui-node", "--config-path", /opt/sui/config/validator1-8080.yaml]

  validator2:
    image: mysten/sui-node:mainnet-v1.55.0-arm64
    depends_on:
      genesis:
        condition: service_completed_successfully
    container_name: validator2
    ports:
      - "9186:9186"
    entrypoint: ["/root/entrypoint.sh"]
    volumes:
      - ./validator/entrypoint.sh:/root/entrypoint.sh:rox
      - validator2_db:/root/.sui/sui_config
      - genesis_config:/opt/sui/config:rw
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=off
      - NAME=validator2
      - RPC_PORT=9186
    command: ["sui-node", "--config-path", /opt/sui/config/validator2-8080.yaml]

volumes:
  fullnode_db:
    driver: local
  validator0_db:
    driver: local
  validator1_db:
    driver: local
  validator2_db:
    driver: local
  genesis_config:
    driver: local
