--- 
services:
  node:
    image: tools:testing
    container_name: node
    ports:
      - "8080:8080"
      - "8084:8084/udp"
      - "9000:9000"
      - "9184:9184"
      - "9123:9123"
    entrypoint: ["/root/entrypoint.sh"]
    volumes:
      - ./fullnode-template.yaml:/root/fullnode.yaml:ro
      - ./genesis.yaml:/root/genesis.yaml:ro
      - ./entrypoint.sh:/root/entrypoint.sh:rox
      - node_config:/root/.sui/sui_config
    environment:
      RUST_BACKTRACE: 1
    command: ["sui", "start", "--with-faucet"]
    healthcheck:
      test: ["CMD-SHELL", "test -f /root/.sui/sui_config/genesis.blob -a -f /root/.sui/sui_config/sui.keystore"]
      interval: 5s
      timeout: 2s
      retries: 10
  
  prometheus:
    image: prom/prometheus:v3.5.0
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:12.1.1
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3000:3000"

  node-exporter:
    image: prom/node-exporter:v1.9.1
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"

  stress:
    image: stress:testing
    depends_on:
      node:
        condition: service_healthy
    environment:
      - RUST_BACKTRACE=1
      - STARTUP_DELAY_SECONDS=5
      - STRESS_STAGGERED_START_MAX_MULTIPLIER=0
      - FULLNODE_RPC_ADDRESS=node:9000
      - PRIMARY_GAS_OWNER=0xca97774fbdbf7539aa14cfad491a227661284e3a3d0b97e6365438745beca509
      - GENESIS_BLOB_PATH=/opt/sui/config/genesis.blob
      - KEYSTORE_PATH=/root/sui.keystore
      - STRESS_TARGET_QPS=100
      - STRESS_SHARED_COUNTER=50
      - STRESS_TRANSFER_OBJECT=50
      - STRESS_DELEGATION=0
      - SUI_PROTOCOL_CONFIG_CHAIN_OVERRIDE=${SUI_PROTOCOL_CONFIG_CHAIN_OVERRIDE}
      - BATCH_PAYMENT=1
      - BATCH_PAYMENT_SIZE=15
      - STRESS_ADVERSARIAL=0
    volumes:
      - node_config:/opt/sui/config:ro
      - ./sui.keystore:/root/sui.keystore:ro

  validator1:
    image: tools:testing
    depends_on:
      node:
        condition: service_healthy
    container_name: validator1
    ports:
      - "9185:9185"
    entrypoint: ["/root/entrypoint.sh"]
    volumes:
      - ./validator1/sui.keystore:/root/sui.keystore:rw
      - ./validator1/entrypoint.sh:/root/entrypoint.sh:rox
      - ./validator1/validator.yaml:/root/validator.yaml:ro
      - ./validator1/client.yaml:/root/.sui/sui_config/client.yaml:ro
      - node_config:/opt/sui/config:ro
      - validator_config:/root/.sui/sui_config
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: off
    command: ["sui-node", "--config-path", /root/validator.yaml]

volumes:
  node_config:
    driver: local
  validator_config:
    driver: local
