global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "Validator_0"
    static_configs:
      - targets: ["host.docker.internal:9184"]
        labels:
          host: validator0
          network: local
  - job_name: "Validator_1"
    static_configs:
      - targets: ["host.docker.internal:9185"]
        labels:
          host: validator1
          network: local
  - job_name: "Validator_2"
    static_configs:
      - targets: ["host.docker.internal:9186"]
        labels:
          host: validator2
          network: local
  - job_name: "node"
    static_configs:
      - targets: ["host.docker.internal:9100"]
        labels:
          host: node
          network: local
