---
protocol-key-pair:
  path: /root/.sui/sui_config/protocol.key
worker-key-pair:
  path: /root/.sui/sui_config/worker.key
network-key-pair:
  path: /root/.sui/sui_config/network.key
db-path: /root/.sui/sui_config/authorities_db
network-address: /dns/validator1/tcp/8080/http
metrics-address: 0.0.0.0:9185
admin-interface-port: 1337
consensus-config:
  db-path: /root/.sui/sui_config/consensus_db
p2p-config:
  listen-address: 0.0.0.0:8084
  external-address: /dns/validator1/udp/8084
  anemo-config:
    max-concurrent-connections: 0
genesis:
  genesis-file-location: /opt/sui/config/genesis.blob
enable-index-processing: false
authority-store-pruning-config:
  num-epochs-to-retain: 0
  num-epochs-to-retain-for-checkpoints: 2
checkpoint-executor-config:
  checkpoint-execution-max-concurrency: 200
  local-execution-timeout-sec: 10
db-checkpoint-config:
  perform-db-checkpoints-at-epoch-end: false
indirect-objects-threshold: 18446744073709551615
